### ISSUE TITLE
Some models should be changed to fit with the drawer scale.

### ISSUE THREAD

**Issue by Toqozz** [DreamforgeStudios/ShonkyShopkeeper#12]
**Is your feature request related to a problem? Please describe.**
The brick (and a few of the jewels) look a little strange when in the drawers because of their shape.  They're quite long on the X axis, whereas the drawers are uniform cubes.  The brick -> golem shell transition also looks a little strange because of this.

![image](https://user-images.githubusercontent.com/6947819/44146178-d22977da-a0d1-11e8-9980-e878036d691a.png)

**Describe the solution you'd like**
Brick, Ruby Jewel, Sapphire Jewel, and Ore should be remodeled to be more of a "snug" square fit in the drawers.  I'd say the same about the regular Sapphire, but I <b>really</b> like the way that it looks.

**Describe alternatives you've considered**
For the Brick at least, we could scale the object manually in the editor:
![image](https://user-images.githubusercontent.com/6947819/44146275-3d1e916a-a0d2-11e8-8355-3880f65da5f6.png)

I don't think that this looks quite right, however.

**Comment by matthewdavies1212** [comment]
Square Brick Implemented

**Comment by matthewdavies1212** [comment]
Sizing of each item adjusted using updated models
