### ISSUE TITLE
Clicking on the resource pouch when using the forceps causes the inventory to become unusable.

### ISSUE THREAD

**Issue by Toqozz** [DreamforgeStudios/ShonkyShopkeeper#3]
**Describe the bug**
See title.

**To Reproduce**
1. Open the game.
2. Select the forceps.
3. Click on a resource pouch.
4. Inventory is stuck and unable to be interacted with.

**Expected behavior**
Pouch raises normally and swaps with a new item when it's selected.

**Additional context**
This is an issue with `Toolbox.cs`

**Comment by matthewdavies1212** [comment]
Issue has been fixed. The Sack prefab was missing the rotate script.
