### ISSUE TITLE
Incorrect pivots on meshes.

### ISSUE THREAD

**Issue by Toqozz** [DreamforgeStudios/ShonkyShopkeeper#5]
**Describe the bug**
The new Amethyst gem has incorrect pivots.

**Expected behavior**
The pivot should be in the center of the object, so rotations rotate the object in-place.  Instead the pivot is off center, which makes rotation difficult.

**Screenshots**
![image](https://user-images.githubusercontent.com/6947819/43839375-42ef03c0-9b61-11e8-9741-79fd2e0e5097.png)

**Comment by matthewdavies1212** [comment]
Seems to be fixed.
